// <auto-generated />
using System;
using LHS_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LHS_API.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20251119105451_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LHS_Models.Models.Account", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74dcce23-2377-4e91-8990-a7c85ab64630"),
                            CreatedDate = new DateTime(2025, 11, 19, 17, 54, 51, 220, DateTimeKind.Local).AddTicks(5804),
                            IsActived = true,
                            Password = "123456",
                            ProfileId = new Guid("856eb7d9-24b2-4743-bd05-624e5f272640"),
                            RoleId = new Guid("fb776600-cf93-4411-8c39-ddc68682b72a"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("74dcce23-2377-4e91-8990-a7c85ab64631"),
                            CreatedDate = new DateTime(2025, 11, 19, 17, 54, 51, 220, DateTimeKind.Local).AddTicks(5817),
                            IsActived = true,
                            Password = "123456",
                            ProfileId = new Guid("856eb7d9-24b2-4743-bd05-624e5f272641"),
                            RoleId = new Guid("fb776600-cf93-4411-8c39-ddc68682b72b"),
                            Username = "pubu"
                        },
                        new
                        {
                            Id = new Guid("74dcce23-2377-4e91-8990-a7c85ab64632"),
                            CreatedDate = new DateTime(2025, 11, 19, 17, 54, 51, 220, DateTimeKind.Local).AddTicks(5820),
                            IsActived = true,
                            Password = "123456",
                            ProfileId = new Guid("856eb7d9-24b2-4743-bd05-624e5f272642"),
                            RoleId = new Guid("fb776600-cf93-4411-8c39-ddc68682b72b"),
                            Username = "nghi"
                        });
                });

            modelBuilder.Entity("LHS_Models.Models.Authorized", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Authorized");

                    b.HasData(
                        new
                        {
                            Id = new Guid("196eb711-24b2-4003-bd05-624e5f552640"),
                            PermissionId = new Guid("186eb711-24b2-4003-bd05-624e5f552640"),
                            RoleId = new Guid("fb776600-cf93-4411-8c39-ddc68682b72a")
                        },
                        new
                        {
                            Id = new Guid("196eb711-24b2-4003-bd05-624e5f552641"),
                            PermissionId = new Guid("186eb711-24b2-4003-bd05-624e5f552641"),
                            RoleId = new Guid("fb776600-cf93-4411-8c39-ddc68682b72a")
                        });
                });

            modelBuilder.Entity("LHS_Models.Models.Department", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("826eb711-24b2-4003-bd05-624e5f552640"),
                            Name = "Sở Nội vụ tỉnh Cà Mau"
                        },
                        new
                        {
                            Id = new Guid("826eb711-24b2-4003-bd05-624e5f552641"),
                            Name = "Hội đồng Nhân dân tỉnh Cà Mau"
                        });
                });

            modelBuilder.Entity("LHS_Models.Models.Permission", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PerCatId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("186eb711-24b2-4003-bd05-624e5f552640"),
                            Code = "view-profile-list",
                            Name = "Xem list profiles",
                            PerCatId = new Guid("176eb711-24b2-4003-bd05-624e5f552641")
                        },
                        new
                        {
                            Id = new Guid("186eb711-24b2-4003-bd05-624e5f552641"),
                            Code = "create-profile",
                            Name = "Tạo profile",
                            PerCatId = new Guid("176eb711-24b2-4003-bd05-624e5f552641")
                        });
                });

            modelBuilder.Entity("LHS_Models.Models.PermissionCategory", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PermissionCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("176eb711-24b2-4003-bd05-624e5f552640"),
                            Name = "Trang Admin"
                        },
                        new
                        {
                            Id = new Guid("176eb711-24b2-4003-bd05-624e5f552641"),
                            Name = "Trang Profile"
                        });
                });

            modelBuilder.Entity("LHS_Models.Models.Profile", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<Guid?>("DepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepId");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("856eb7d9-24b2-4743-bd05-624e5f272640"),
                            IdNumber = "000000000000",
                            Name = "ADMINISTRATOR",
                            PhoneNumber = "012345678"
                        },
                        new
                        {
                            Id = new Guid("856eb7d9-24b2-4743-bd05-624e5f272641"),
                            DateOfBirth = new DateOnly(2001, 10, 20),
                            DepId = new Guid("826eb711-24b2-4003-bd05-624e5f552640"),
                            IdNumber = "000000000000",
                            Name = "Pu Bu",
                            PhoneNumber = "012345678"
                        },
                        new
                        {
                            Id = new Guid("856eb7d9-24b2-4743-bd05-624e5f272642"),
                            DateOfBirth = new DateOnly(2002, 11, 17),
                            DepId = new Guid("826eb711-24b2-4003-bd05-624e5f552641"),
                            IdNumber = "000000000000",
                            Name = "Nghi Nghi",
                            PhoneNumber = "012345678"
                        });
                });

            modelBuilder.Entity("LHS_Models.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuestionBankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionBankId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("LHS_Models.Models.QuestionBank", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuestionBanks");
                });

            modelBuilder.Entity("LHS_Models.Models.Role", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fb776600-cf93-4411-8c39-ddc68682b72a"),
                            RoleCode = "TNCM_ADM",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("fb776600-cf93-4411-8c39-ddc68682b72b"),
                            RoleCode = "TNCM_CONGCHUC",
                            RoleName = "Công chức"
                        },
                        new
                        {
                            Id = new Guid("fb776600-cf93-4411-8c39-ddc68682b72c"),
                            RoleCode = "TNCM_VIENCHUC",
                            RoleName = "Viên chức"
                        },
                        new
                        {
                            Id = new Guid("fb776600-cf93-4411-8c39-ddc68682b72d"),
                            RoleCode = "TNCM_OTHER",
                            RoleName = "Khác"
                        });
                });

            modelBuilder.Entity("LHS_Models.Models.TestHandler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TestTimeCountdown")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("TestHandlers");
                });

            modelBuilder.Entity("LHS_Models.Models.TestRecord", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TestHandlerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TestHandlerId");

                    b.ToTable("TestRecords");
                });

            modelBuilder.Entity("LHS_Models.Models.Account", b =>
                {
                    b.HasOne("LHS_Models.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LHS_Models.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LHS_Models.Models.Profile", b =>
                {
                    b.HasOne("LHS_Models.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("LHS_Models.Models.Question", b =>
                {
                    b.HasOne("LHS_Models.Models.QuestionBank", "Bank")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionBankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("LHS_Models.Models.TestHandler", b =>
                {
                    b.HasOne("LHS_Models.Models.QuestionBank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("LHS_Models.Models.TestRecord", b =>
                {
                    b.HasOne("LHS_Models.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LHS_Models.Models.TestHandler", "TestHandler")
                        .WithMany("TestRecord")
                        .HasForeignKey("TestHandlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("TestHandler");
                });

            modelBuilder.Entity("LHS_Models.Models.QuestionBank", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LHS_Models.Models.TestHandler", b =>
                {
                    b.Navigation("TestRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
